package com.appharbor.photosender.ui.theme

import androidx.compose.ui.graphics.Color

// Azure Stream Design System — Light Mode
val PrimaryLight = Color(0xFF0040A1)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFF0056D2)
val OnPrimaryContainerLight = Color(0xFFFFFFFF)
val PrimaryFixedLight = Color(0xFFDAE2FF)
val PrimaryFixedDimLight = Color(0xFFB2C5FF)

val SecondaryLight = Color(0xFF2B4CDA)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFF4967F4)
val OnSecondaryContainerLight = Color(0xFFFFFFFF)

val TertiaryLight = Color(0xFF005136)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFF006C49)
val OnTertiaryContainerLight = Color(0xFFFFFFFF)
val TertiaryFixedLight = Color(0xFF6FFBBE)
val TertiaryFixedDimLight = Color(0xFF4EDEA3)

val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)

val SurfaceLight = Color(0xFFFBF8FE)
val OnSurfaceLight = Color(0xFF1B1B1F)
val SurfaceDimLight = Color(0xFFDDD9E0)
val SurfaceBrightLight = Color(0xFFFBF8FE)
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SurfaceContainerLowLight = Color(0xFFF6F2F8)
val SurfaceContainerLight = Color(0xFFF0EDF2)
val SurfaceContainerHighLight = Color(0xFFEAE7EC)
val SurfaceContainerHighestLight = Color(0xFFE4E1E7)
val OnSurfaceVariantLight = Color(0xFF44464F)
val OutlineLight = Color(0xFF737785)
val OutlineVariantLight = Color(0xFFC3C6D6)
val InverseSurfaceLight = Color(0xFF303034)
val InverseOnSurfaceLight = Color(0xFFF2F0F4)
val InversePrimaryLight = Color(0xFFB2C5FF)

// Azure Stream Design System — Dark Mode
val PrimaryDark = Color(0xFFB2C5FF)
val OnPrimaryDark = Color(0xFF002B75)
val PrimaryContainerDark = Color(0xFF0056D2)
val OnPrimaryContainerDark = Color(0xFFDAE2FF)

val SecondaryDark = Color(0xFFBEC6FF)
val OnSecondaryDark = Color(0xFF0026A0)
val SecondaryContainerDark = Color(0xFF4967F4)
val OnSecondaryContainerDark = Color(0xFFDEE0FF)

val TertiaryDark = Color(0xFF4EDEA3)
val OnTertiaryDark = Color(0xFF00391F)
val TertiaryContainerDark = Color(0xFF006C49)
val OnTertiaryContainerDark = Color(0xFF6FFBBE)

val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)

val SurfaceDark = Color(0xFF121316)
val OnSurfaceDark = Color(0xFFE4E1E7)
val SurfaceDimDark = Color(0xFF121316)
val SurfaceBrightDark = Color(0xFF38393D)
val SurfaceContainerLowestDark = Color(0xFF0D0E11)
val SurfaceContainerLowDark = Color(0xFF1A1B1F)
val SurfaceContainerDark = Color(0xFF1E1F23)
val SurfaceContainerHighDark = Color(0xFF292A2E)
val SurfaceContainerHighestDark = Color(0xFF343539)
val OnSurfaceVariantDark = Color(0xFFC3C6D6)
val OutlineDark = Color(0xFF8D909F)
val OutlineVariantDark = Color(0xFF44464F)
val InverseSurfaceDark = Color(0xFFE4E1E7)
val InverseOnSurfaceDark = Color(0xFF303034)
val InversePrimaryDark = Color(0xFF0040A1)