package com.appharbor.pherry.ui.components

import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.semantics.clearAndSetSemantics
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import com.appharbor.pherry.R
import com.appharbor.pherry.ui.theme.PherryTheme

/**
 * The Pherry mark: a "P" cut from film (sprocket stem, frame window) on envelope yellow. The same
 * artwork as the launcher icon, generated by docs/brand/build_brand.py.
 */
@Composable
fun PherryMark(
    modifier: Modifier = Modifier,
    size: Dp = 28.dp,
) {
    Image(
        painter = painterResource(R.drawable.ic_pherry_logo),
        contentDescription = null,
        modifier = modifier.size(size),
    )
}

@Composable
fun PherryWordmark(
    modifier: Modifier = Modifier,
    markSize: Dp = 28.dp,
    color: Color = PherryTheme.colors.ink,
) {
    Row(
        modifier = modifier.clearAndSetSemantics { contentDescription = "Pherry" },
        verticalAlignment = Alignment.CenterVertically,
    ) {
        PherryMark(size = markSize)
        Spacer(Modifier.width(10.dp))
        Text(text = "Pherry", style = PherryTheme.text.wordmark, color = color)
    }
}
